### ISSUE TITLE
Can't compile with json4s 

### ISSUE THREAD

**Issue by seanmcl** [scala-js/scala-js-website#149]
I'm trying out ScalaJS, and just made a little program that makes a simple Ajax request and tries to parse it with json4s.  The code compiles fine, but the optimizer fails with the message below.  json4s uses reflection via `extract`.  The claim on the ScalaJS is that it supports all of scala, so it seems this should be allowed.  Is there something else I'm doing wrong?  Perhaps the implicit DefaultFormats is somehow not compiled to Javascript?

```
[info] Fast optimizing /foo/target/scala-2.11/example-fastopt.js
[error] Referring to non-existent class Lorg_json4s_DefaultFormats$
```

```scala
import org.scalajs.dom.ext.Ajax
import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue

import org.json4s.DefaultFormats
import org.json4s.native.JsonMethods.parse

object Pagerduty {
  type Json = org.json4s.JsonAST.JValue
  val token = "foo"
  implicit val formats = DefaultFormats

  def onCall: Future[EscalationPolicy] =
    Ajax.get(
      url = "https://eglp.pagerduty.com/api/v1/escalation_policies/on_call"
    ) map (xhr => parse(xhr.responseText).extract[EscalationPolicy])
}
```

PS: ScalaJS is a nice project.

**Comment by sjrd** [comment]
First, as a user question, this should be posted on [Stack Overflow](http://stackoverflow.com/questions/tagged/scala.js), not in Issues. I'll answer and close. If you need more detail, please ask on SO.

Scala.js supports all of Scala, modulo [a few semantic differences](http://www.scala-js.org/doc/semantics.html), as clearly stated in the front page. And run-time reflection is listed there as not supported.

But that is not your issue. The issue is that you are using a library that was not compiled for Scala.js. In general you have to use the `%%%` artifacts in sbt rather than `%%` artifacts. But that still requires the given library to compile with Scala.js and publish the artifacts. Usually, when they do, they clearly advertise it on their Readme. json4s doesn't do that, so you cannot use json4s directly.

But in Scala.js there is much more direct way to parse JSON:
```scala
import scala.scalajs.js

js.JSON.parse(xhr.responseText)
```
and that's all.

**Comment by seanmcl** [comment]
Apologies. Thanks for the detailed answer.
